cms/core/urls.py
from django.conf.urls.defaults import patterns

urlpatterns = patterns('cms.core.views',
    ('^(?P<site>[^/]*)(?P<path>.*)/__history__/$', 'entry_history'),
    ('^(?P<site>[^/]*)(?P<path>.*)/__contents__/$', 'entry_contents'),
    ('^(?P<site>[^/]*)(?P<path>.*)/__edit__/$', 'edit_entry'),
    ('^(?P<site>[^/]*)(?P<path>.*)/__state__/(?P<new_state_id>.*)/$',
                                                            'change_state'),
    ('^(?P<site>[^/]*)(?P<parent_path>.*)/__newpage__/$', 'create_new_page'),
    ('^(?P<site>[^/]*)(?P<path>.*)/__logout__/$', 'logout'),
    ('^(?P<site>[^/]*)(?P<path>.*)/__login__/$', 'login'),
    ('^(?P<site>[^/]*)(?P<path>.*)/$', 'view_object'),
)

urls.py
from django.conf.urls import patterns, include

# Admin
from django.contrib import admin
admin.autodiscover()
urlpatterns = patterns('',
    (r'^__admin__/', admin.site.urls)
)

# Static files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

# Cms
urlpatterns += patterns('',
    (r'^tinymce/', include('tinymce.urls')),
    (r'^', include('zadig.core.urls')),
)

zadig/core/urls.py
from django.conf.urls import patterns

urlpatterns = patterns('zadig.core.views',
    ('^$', 'action_dispatcher'),
    ('^(?P<path>.*)/$', 'action_dispatcher'),
)

cms/core/models.py
from django.db import transaction
from django.core import urlresolvers
from django.db import models
from django.core.exceptions import PermissionDenied
from django.utils.translation import ugettext as _
import django.contrib.auth.models
import settings

class permissions:
    VIEW=1
    EDIT=2
    ADMIN=3
    DELETE=4
    SEARCH=5

class Language(models.Model):
    id = models.CharField(max_length=5, primary_key=True)
    def __unicode__(self):
        return self.id
    class Meta:
        db_table = 'cms_language'

class Permission(models.Model):
    descr = models.CharField(max_length=31)
    def __unicode__(self):
        return self.descr
    class Meta:
        db_table = 'cms_permission'

class Lentity(models.Model):
    """A Lentity represents either a user or a group, and is used whenever any
    of the two can be used; for example, a certain permission can be given
    either to a user or to a group.  Either user, or group, or special, must
    be not null; the other two must be null. If user is not null, the Lentity
    represents a user. If group is not null, the Lentity represents a group. If
    special is 1, it represents the anonymous user, and if special is 2, it
    represents all valid users (the logged on user)."""
    user = models.ForeignKey(django.contrib.auth.models.User, null=True)
    group = models.ForeignKey(django.contrib.auth.models.Group, null=True)
    special = models.PositiveSmallIntegerField(null=True)
    def __unicode__(self):
        return "user=%s, group=%s, special=%s" % (str(self.user),
            str(self.group), str(self.special))
    class Meta:
        unique_together = ('user', 'group')
        db_table = "cms_lentity"
    def save(self, force_insert=False, force_update=False):
        """Verify integrity before saving."""
        if (not self.user and not self.group and self.special in (1, 2)) \
        or (self.user and not self.group and not self.special) \
        or (not self.user and self.group and not self.special):
            return super(Lentity, self).save(force_insert, force_update)
        raise Exception("Invalid Lentity: " + self.__unicode__())

class State(models.Model):
    descr = models.CharField(max_length=31)
    def __unicode__(self):
        return self.descr
    class Meta:
        db_table = 'cms_state'

class StatePermission(models.Model):
    state = models.ForeignKey(State)
    lentity = models.ForeignKey(Lentity)
    permission = models.ForeignKey(Permission)
    def __unicode__(self):
        return "state=%s, %s, permission=%s" (self.state, self.lentity,
                                                            self.permission)
    class Meta:
        unique_together = ('lentity', 'permission')
        db_table = 'cms_statepermission'

class StateTransition(models.Model):
    source_state = models.ForeignKey(State, related_name='source_rules')
    target_state = models.ForeignKey(State, related_name='target_rules')
    def __unicode__(self):
        return "%s => %s" % (self.source_state, self.target_state)
    class Meta:
        unique_together = ('source_state', 'target_state')
        db_table = 'cms_statetransition'

class Workflow(models.Model):
    name = models.CharField(max_length=127, unique=True)
    states = models.ManyToManyField(State)
    state_transitions = models.ManyToManyField(StateTransition)
    def __unicode__(self):
        return self.name
    class Meta:
        db_table = 'cms_workflow'

class Site(models.Model):
    name = models.SlugField(max_length=100, unique=True)
    language = models.ForeignKey(Language)
    workflow = models.ForeignKey(Workflow)
    def __unicode__(self):
        return self.name
    class Meta:
        db_table = 'cms_site'

class EntryManager(models.Manager):
    def get_by_path(self, request, site, path):
        entry=None
        for name in path.split('/'):
            entry = self.get(site__name=site, name=name, container=entry)
            if not permissions.VIEW in entry.get_permissions(request):
                return None
        return entry

class Entry(models.Model):
    site = models.ForeignKey(Site)
    container = models.ForeignKey('self', related_name="all_subentries",
                                  blank=True, null=True)
    name = models.SlugField(max_length=100, blank=True)
    seq = models.PositiveIntegerField()
    owner = models.ForeignKey(django.contrib.auth.models.User)
    state = models.ForeignKey(State)
    objects = EntryManager()
    def __init__(self, *args, **kwargs):
        # If called with only three arguments, then it is someone calling the
        # twistyCMS API, and the three arguments are request, site_name, path.
        # Otherwise, it is likely Django calling us in the default Django way.
        if len(args)!=3 or kwargs:
            return super(Entry, self).__init__(*args, **kwargs)
        (request, site_name, path) = args
        names = path.split('/')
        parent_path = '/'.join(names[:-1])
        parent_entry = Entry.objects.get_by_path(request,site_name, parent_path)
        if not permissions.EDIT in parent_entry.get_permissions(request):
            raise PermissionDenied(_(u"Permission denied"))
        site = Site.objects.get(name=site_name)
        siblings = Entry.objects.filter(container=parent_entry)
        if siblings.count():
            max_seq = siblings.order_by('-seq')[0].seq
        else:
            max_seq = 0
        initial_state = Workflow.objects.get(id=settings.WORKFLOW_ID) \
            .state_transitions.get(source_state__descr="Nonexistent") \
            .target_state
        return super(Entry, self).__init__(site=site, container=parent_entry,
            name=names[-1], owner=request.user, state=initial_state,
            seq = max_seq+1)
    def get_permissions(self, request):
        if request.user.is_authenticated() and self.owner.pk == request.user.pk:
            return set((permissions.VIEW, permissions.EDIT, permissions.ADMIN,
                permissions.DELETE, permissions.SEARCH))
        result = set()
        if request.user.is_authenticated():
            lentities = [Lentity.objects.get(user=request.user),
                         Lentity.objects.get(special=2)]
            lentities.append(Lentity.objects.filter(
                                          group__in=request.user.groups.all()))
        else:
            lentities = [Lentity.objects.get(special=1)]
        for lentity in lentities:
            for perm in EntryPermission.objects.filter(lentity=lentity,
                                                              entry=self):
                result.add(perm.permission_id)
            for perm in StatePermission.objects.filter(lentity=lentity,
                                                              state=self.state):
                result.add(perm.permission_id)
        return result
    def get_vobject(self, request, version_number=None):
        latest_vobject = self.vobject_set.latest()
        if version_number is None:
            vobject = latest_vobject
        else:
            vobject = self.vobject_set.get(version_number=version_number)
        if vobject.version_number != latest_vobject.version_number \
                and permissions.EDIT not in self.get_permissions(request):
            raise PermissionDenied(_(u"Permission denied"))
        return vobject
    @property
    def path(self):
        result = self.name
        entry = self
        while entry.container:
            entry = entry.container
            result = entry.name + '/' + result
        return result
    @property
    def url(self):
        return urlresolvers.reverse('cms.core.views.view_object',
            kwargs = { 'site': self.site.name, 'path': self.path })
    def contains(self, entry):
        while entry:
            if entry.container == self: return True
            entry = entry.container
        return False
    def get_subentries(self, request):
        parent_permissions = self.get_permissions(request)
        if permissions.VIEW not in parent_permissions:
            raise PermissionDenied(_(u"Permission denied"))
        subentries = self.all_subentries.order_by('seq').all()
        if permissions.EDIT in parent_permissions:
            return subentries
        result = []
        for s in subentries:
            if permissions.SEARCH in s.get_permissions(request):
                result.append(s)
        return result
    @transaction.commit_manually
    def reorder(self, request, source_seq, target_seq):
        if permissions.EDIT not in self.get_permissions(request):
            raise PermissionDenied(_(u"Permission denied"))
        try:
            subentries = self.all_subentries.order_by('seq').all()
            s = source_seq
            t = target_seq
            n = len(subentries)
            if s<1 or s>n or t<1 or t>n+1 or s==t:
                raise Exception(_("Invalid reordering operation"))
            subentries[s-1].seq = 32767
            subentries[s-1].save()
            if t>s:
                for i in range(source_seq+1, t):
                    subentries[i-1].seq = i-1
                    subentries[i-1].save()
                subentries[s-1].seq = t-1
                subentries[s-1].save()
            else:
                for i in range(s-1, t-1, -1):
                    subentries[i-1].seq = i+1
                    subentries[i-1].save()
                subentries[s-1].seq = t
                subentries[s-1].save()
        except:
            transaction.rollback()
            raise
        else:
            transaction.commit()
    def __unicode__(self):
        result = self.name
        container = self.container
        while container:
            result = container.name + '/' + result
            container = container.container
        return self.site.__unicode__() + result
    class Meta:
        unique_together = (('site', 'container', 'name'),
                           ('site', 'container', 'seq'))

zadig/core/templates/base-default.html
{% load standard_applets %}
{% load i18n %}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  {% block htmlhead %}
    <title>
      {% block htmltitle %}
        {{vobject.metatags.default.title}}
      {% endblock %}
    </title>
    {% block css %}
      <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}style.css"
          title="style" />
    {% endblock %}
    {% block favicon %}
      <link rel="shortcut icon" href="/__static__/zadig-icon.ico" />
    {% endblock %}
    {% block js %}
      <script src="{{STATIC_URL}}utils.js"></script>
      <script src="{{STATIC_URL}}zadig.js"></script>
    {% endblock %}
    {% block base %}
      <base href="{{vobject.entry.absolute_uri}}" />
    {% endblock %}
    {% block extrahead %}{% endblock %}
  {% endblock %}
</head>

<body>
  <div id="portalTop">
    {% block top %}
      {% block logo %}
        <img style="padding: 5px 5px 5px 20px;" src="/__static__/zadig-icon.png" />
      {% endblock %}
      <div id="portalPersonaltools">
        {% block personaltools %}
          {% login %}
        {% endblock %}
      </div>
      <div id="toolLine">
        {% block toolline %}
          <div id="portalBreadcrumbs">
            {% trans "You are here: " %}{% breadcrumbs %}
          </div>
          <div id="languageTools">
            {% language_tools %}
          </div>
        {% endblock %}
      </div>
    {% endblock %}
  </div>
  <table id="portalColumns">
    <tbody>
    <tr>
      <td id="leftColumn">
        {% block leftpane %}
          {% navigation %}
        {% endblock %}
      </td>
      <td id="mainColumn">
        {% block buttons %}
          {% primary_buttons %}
          {% secondary_buttons %} 
        {% endblock %}
        <div class="mainContent {% if vobject.entry.touchable %}withButtons{% endif %}">
          {% block message %}
            {% if vobject.request.message %}
              <p class="message">{{ vobject.request.message }}</p>
            {% endif %}
          {% endblock %}
          {% block mainContent %}
          {% endblock %}
          {% block mainAdditions %}
          {% endblock %}
        </div>
      </td>
      <td id="rightColumn">
        {% block rightpane %}
          {% news %}
          {% events %}
        {% endblock %}
      </td>
    </tr>
    </tbody>
  </table>
  <div id="portalBottom">
    {% block bottom %}
      <div id="portalFooter">
        {% block footer %}
        {% endblock %}
      </div>
      <div id="portalColophon">
        {% block colophon %}
          <ul>
            <li>Powered by
            <a href="https://github.com/aptiko/zadig/">Zadig</a></li>
          </ul>
        {% endblock %}
      </div>
    {% endblock %}
  </div>
</body>
</html>

zadig/core/templates/base-example.html
{% extends "base-default.html" %}

zadig/core/templates/edit_entry.html
{% extends vobject.entry.base_template %}
{% load i18n %}

{% block mainContent %}
  <h1>Edit {{vobject.entry.name}}</h1>
  <form class="editObject" enctype="multipart/form-data" action="{{ vobject.entry.spath }}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="action" value="{{ request.action }}" />
  <input type="hidden" name="entry_type" value="{{ object_type }}" />
  <table>
    <tr><td colspan="2">{{ mainform.non_field_errors }}</td></tr>
    <tr>
      <td>{{ mainform.name.errors }}
           <label for="id_name">{% trans "Name:" %}</label>
           {{mainform.name}}
      </td>
      <td>{{ mainform.language.errors }}
           <label for="id_language">{% trans "Language:" %}</label>
           {{mainform.language}}
      </td>
      <td>{{ mainform.altlang.errors }}
           <label for="id_altlang">{% trans "Alternative:" %}</label>
           {{mainform.altlang}}
      </td>
    </tr>
  </table>
  <table>
    {{ metatagsformset.as_wide_table }}
  </table>
  {{ subform.non_field_errors }} <table>{{subform.render|safe}}</table>
  {% for f in optionsforms %}
    {{f.non_field_errors}}<table>{{f.as_table}}</table>
  {% endfor %}
  <input type="submit" value="Submit" />
  </form>
{% endblock %}

zadig/core/templates/entry_contents.html
{% extends vobject.entry.base_template %}
{% load i18n %}

{% block mainContent %}
  <h1>Contents of {{vobject.metatags.default.get_short_title}}</h1>
  <form method="POST" action="{{ vobject.entry.spath }}">
    {% csrf_token %}
    <input type="hidden" name="action" value="contents" />
    {{ formset.management_form }}
    <table class="listing objectContents">
      <thead><tr>
          <th></th>
          <th></th>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Title" %}</th>
          <th>{% trans "Type" %}</th>
      </tr></thead>
      <tbody>
        {% for s,f in subentries_with_formset %}
          <tr><td>{{ s.seq }}</td>
              <td>{{ f.select_object }}</td>
              <td><a class="state{{s.state|cut:' '}}" href="{{s.spath}}__info__/">{{s.name}}</a></td>
              <td>{{ s.vobject.metatags.default.get_short_title }}</td>
              <td>{{s.descendant.typename}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <input type="submit" name="cut" value="Cut selected objects" />
    <table><tbody>{{ move_item_form.as_table }}</tbody></table>
    <input type="submit" name="move" value="Move"/>
  </form>
{% endblock %}

zadig/core/templates/entry_history.html
{% extends vobject.entry.base_template %}
{% load i18n %}

{% block mainContent %}
  <h1>History of {{vobject.entry.name}}</h1>
  <table class="objectContents">
    <tbody>
    {% for v in vobject.entry.vobject_set.all.reverse %}
        <tr><td>{{ v.version_number }}.</td>
            <td>{{ v.date|date:"Y-m-d H:i:s" }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

zadig/core/templates/entry_permissions.html
{% extends vobject.entry.base_template %}
{% load i18n %}

{% block mainContent %}
  <h1>Permissions of {{vobject.metatags.default.get_short_title}}
  (/{{vobject.entry.name}}) </h1>
  <form action="." method="POST">
    {% csrf_token %}
    <table>
    {{permissions_form.as_table}}
    </table>
    <input type="hidden" name="action" value="permissions" />
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

zadig/core/templates/login.html
{% extends vobject.entry.base_template %}

{% block mainContent %}
  <h1>Login</h1>
  <form class="login" action="{{ vobject.entry.spath }}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="action" value="login" />
  <table>
  {{form.as_table}}
  </table>
  <input type="submit" value="Submit" />
  </form>
{% endblock %}

zadig/core/templates/view_deleted_entry.html
{% extends vobject.entry.base_template %}
{% load i18n %}

{% block htmltitle %}
  Object not found
{% endblock %}

{% block mainContent %}
  <h1>{% trans "This object has been deleted" %}</h1>
  <form method="POST" action="{{vobject.entry.spath}}">
  {% csrf_token %}
  <input type="hidden" name="action" value="undelete"/>
  <input type="submit" value="{% trans "Undelete" %}"/>
  </form>
{% endblock %}